Repository woowa-techcamp-2021/deal-13, pull requests merged in 2021-07, with the labels that each got.

#2 [#1] wip: 공통 개발 환경 구성 - 1
  .gitignore
  package-lock.json
  package.json
Labels: be, fe

#3 [#1] wip: 공통 개발 환경 구성 - 2
  .babelrc
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  tsconfig.json
  webpack.config.js
Labels: fe

#8 백엔드 개발 환경 구성 완료
  .gitignore
  package-lock.json
  package.json
  src/main.js
  src/models/index.js
  tsconfig.json
Labels: be

#25 [#7] wip: ⚙️ db sequelize 제거 후 db 연결 - 1
  package-lock.json
  package.json
  src/db/index.js
  src/main.js
  src/models/index.js
Labels: be

#27 [#26] refactor: tsconfig 수정
  tsconfig.json
  webpack.config.js
Labels: be, fe

#29 [#28] refactor: 클라이언트 서버 디렉토리 분리
  .gitignore
  client/.babelrc
  client/.eslintrc.json
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/app.ts
  client/src/index.html
  client/webpack.config.js
  server/.eslintrc.json
  server/.prettierrc
  server/package-lock.json
  server/package.json
  server/src/db/index.js
  server/src/main.js
  tsconfig.json
Labels: be, fe

#33 [#9] wip: 최상위 모듈 기본틀 완성
  client/src/app.ts
  client/src/components/Account.ts
  client/src/components/Category.ts
  client/src/components/Chatting.ts
  client/src/components/ChattingDetail.ts
  client/src/components/Login.ts
  client/src/components/Main.ts
  client/src/components/Menu.ts
  client/src/components/Post.ts
  client/src/components/Region.ts
  client/src/components/Signin.ts
  client/src/components/Write.ts
  client/src/index.html
  client/src/styles/App.scss
Labels: fe

#34 [#6] wip: 공통 UI 현재까지의 작업 내용 입니다.
  client/package-lock.json
  client/package.json
  client/src/layout-example.html
  client/src/public/images/add.svg
  client/src/public/images/category.svg
  client/src/public/images/check.svg
  client/src/public/images/close.svg
  client/src/public/images/down.svg
  client/src/public/images/hear.svg
  client/src/public/images/image.svg
  client/src/public/images/left.svg
  client/src/public/images/logout.svg
  client/src/public/images/menu.svg
  client/src/public/images/message.svg
  client/src/public/images/more.svg
  client/src/public/images/pin.svg
  client/src/public/images/right.svg
  client/src/public/images/send.svg
  client/src/public/images/user.svg
  client/src/styles/index.scss
  client/src/styles/mixins.scss
  client/src/styles/reset.scss
  client/src/styles/variables.scss
  client/webpack.config.js
Labels: fe

#35 [#6, #12] wip: 로그인 관련 내용입니다.
  server/src/main.js
  server/src/passport/index.js
  server/src/routes/auth.js
Labels: be

#38 [#6] 공통 스타일, UI 구현 완료
  client/src/layout-example.html
  client/src/public/images/heart.svg
  client/src/styles/index.scss
  client/src/styles/variables.scss
Labels: fe

#39 [#9] 메인화면 프론트엔드 대략적인 완성?
  client/src/app.ts
  client/src/components/Main.ts
  client/src/styles/App.scss
  client/webpack.config.js
Labels: fe

#41 #9 메인화면 및 메인모듈 완성?
  client/src/app.ts
  client/src/components/Main.ts
  client/src/styles/Main.scss
  client/src/styles/index.scss
Labels: fe

#42 [#13] wip: 카테고리 UI 구현 작업 중
  client/src/components/Category.ts
  client/src/styles/index.scss
Labels: fe

#43 [#15] wip: 메뉴 UI 작업 중
  client/src/components/Menu.ts
  client/src/styles/index.scss
  client/src/styles/menu.scss
  client/src/styles/mixins.scss
Labels: fe

#44 [#9] 메인화면 자잘한거 추가, 로그인 기능 구현
  client/src/components/Login.ts
  client/src/components/Main.ts
  client/src/styles/Login.scss
  client/src/styles/Main.scss
Labels: fe

#45 #12 Be/auth 완성?
  server/src/passport/index.js
  server/src/routes/auth.js
Labels: be

#48 [#11] bug: 내계정에서 뒤로가기 추가
  client/src/app.ts
  client/src/components/Account.ts
Labels: fe

#50 금요일 배포버전 리팩토링
  client/src/app.ts
  client/src/components/Account.ts
  client/src/components/Category.ts
  client/src/components/Chatting.ts
  client/src/components/ChattingDetail.ts
  client/src/components/Login.ts
  client/src/components/Main.ts
  client/src/components/Menu.ts
  client/src/components/Post.ts
  client/src/components/Region.ts
  client/src/components/Signup.ts
  client/src/components/Write.ts
  server/src/routes/auth.js
Labels: fe

#72 [#18] wip: API user_id 삭제 및 상품 상세 쿼리에 지역 이름 추가
  server/src/controllers/goods-wish.controller.js
  server/src/controllers/goods.controller.js
  server/src/queries/goods.query.js
  server/src/routes/goods.js
Labels: be

#74 [#18] bug: join region 추가
  server/src/queries/goods.query.js
Labels: fix

#82 [#13, #18] category, goods 수정
  client/src/app.ts
  client/src/components/Category.ts
  client/src/components/Main.ts
  client/src/styles/Category.scss
  server/src/queries/goods.query.js
  server/src/routes/category.js
  server/src/services/goods.service.js
Labels: be, bug, fe, fix
